import "@/styles/globals.css";
import Head from "next/head";
import Layout from "@/components/layout";
import type { AppProps } from "next/app";

const MyApp = ({ Component, pageProps }: AppProps) => {
  const children = <Component {...pageProps} />;
  return (
    <>
      <Head>
        <title>PLAY</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>{children}</Layout>
    </>
  );
};

export default MyApp;
