import "@/styles/globals.scss";
import { Suspense } from "react";
import { Provider } from "react-redux";
import { store } from "@/storage";
import Head from "next/head";
import Layout from "@/components/layout";
import type { AppProps } from "next/app";
import Loading from "@/components/loader";

const MyApp = ({ Component, pageProps }: AppProps) => {
  const children = <Component {...pageProps} />;
  return (
    <>
      <Suspense fallback={<Loading/>}>
        <Head>
          <title>Next</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Provider store={store}>
          <Layout>{children}</Layout>
        </Provider>
      </Suspense>
    </>
  );
};

export default MyApp;
